### ISSUE TITLE
#8 Som bruker skal jeg kunne hente ut rapporter av valgfrie betalingsmetoder og for valgfritt tidsspenn for å registrere i regnskap / google sheets

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/effekt-admin#38]
- [x] #65 Checkbox UI komponent
- [x] #66 Switch UI komponent
- [x] stiftelsen-effekt/effekt-backend#68 Skriv om backend
- [x] #67 Actions og sagas for nedlasting av rapporter
